프라미스 핸들러 `.then/catch/finally`
* 항상 비동기적으로 실행
* 프라미스가 즉시 이행되어라도 아래에 있는 코드(동기)가 이 핸들러들이 실행되기 전에 실행

```javascript
let promise = Promise.resolve();

promise.then(() => console.log("프라미스 성공!"));

console.log("코드 종료");
```
출력 결과
1. "코드 종료"
2. "프라미스 성공!"

왜 그럴까?

# 마이크로태스크 큐
비동기 작업 처리를 위해 큐를 사용해 관리합니다.
* ECMA > `PromiseJobs`라는 내부 큐(internal queue)
* V8 엔진 > 마이크로태스크 큐(microtask queue) : 이 용어가 좀 더 선호됨

[명세서](https://tc39.es/ecma262/#sec-jobs-and-job-queues) 의 설명을 살펴봅시다.
* 마이크로태스크 큐는 먼저 들어온 작업을 먼저 실행합니다.(FIFO, first-in-first-out)
* **실행할 것이 아무것도 남아있지 않을 때**만 마이크로태스크 큐에 있는 작업이 실행되기 시작합니다.

=> 어떤 프라미스가 준비되었을 때 이 프라미스의 `then/catch/finally`핸들러가 큐에 들어갑니다.
이때 핸들러들은 여전히 실행되지 않고, 현재 코드에서 자유로운 상태가 되었을 때 자바스크립트 엔진은 큐에서 작업을 꺼내 실행합니다.

프라미스 핸들러는 항상 내부 큐를 통과합니다.

여러 개의 `.then/catch/finally`를 사용해 만든 체인의 경우, 각 핸들러는 비동기적으로 실행됩니다.
큐에 들어간 핸들러 각각은 현재 코드가 완료되고, 큐에 적체된 이전 핸들러의 실행이 완료되었을 때 실행됩니다.

그렇다면 '프라미스 성공!'을 먼저, '코드 종료’를 나중에 출력되게 하려면 어떻게 해야 할까요?

=> `.then`을 사용해 큐에 넣는다.

```javascript
Promise.resolve()
  .then(() => console.log("프라미스 성공!"))
  .then(() => console.log("코드 종료"));
```
출력 결과
1. "프라미스 성공!"
2. "코드 종료"

# 처리되지 못한 거부
"프라미스와 에러 핸들링"에서 학습한 `unhandledrejection` 이벤트를 기억하고 계시나요?

이제 자바스크립트 엔진이 어떻게 처리되지 못한 거부(unhandled rejection)를 찾는지 정확히 알 수 있습니다.

**’처리되지 못한 거부’는 마이크로태스크 큐 끝에서 프라미스 에러가 처리되지 못할 때 발생합니다.**

정상적인 경우라면 개발자는 에러가 생길 것을 대비하여 프라미스 체인에 `.catch`를 추가해 에러를 처리합니다.

```javascript
let promise = Promise.reject(new Error("프라미스 실패!"));
promise.catch(err => console.log('잡았다!'));

// 에러가 잘 처리되었으므로 실행되지 않습니다.
window.addEventListener('unhandledrejection', event => console.log(event.reason));
```

`.catch`를 추가해주는 걸 잊은 경우, 엔진은 마이크로태스크 큐가 빈 이후에 `unhandledrejection` 이벤트를 트리거 합니다.
```javascript
let promise = Promise.reject(new Error("프라미스 실패!"));

// 프라미스 실패!
window.addEventListener('unhandledrejection', event => console.log(event.reason));
```

그런데 만약 아래와 같이 setTimeout을 이용해 에러를 나중에 처리하면 어떤 일이 생길까요?

```javascipt
let promise = Promise.reject(new Error("프라미스 실패!"));
setTimeout(() => promise.catch(err => console.log('잡았다!')), 1000);

// Error: 프라미스 실패!
window.addEventListener('unhandledrejection', event => console.log(event.reason));
```

출력 결과
* 프라미스 실패!
* 잡았다!

**`unhandledrejection`은 마이크로태스크 큐에 있는 작업 모두가 완료되었을 때 생성**됩니다.
엔진은 프라미스들을 검사하고 이 중 하나라도 ‘거부(rejected)’ 상태이면 `unhandledrejection` 핸들러를 트리거 하죠.
이로써 앞선 의문이 자연스레 해결되었습니다.

위 예시를 실행하면 `setTimeout`을 사용해 추가한 `.catch` 역시 트리거 됩니다.
다만 **`.catch`는 `unhandledrejection`이 발생한 이후에 트리거** 되므로 프라미스 실패!가 출력됩니다.
