## async와 await

### async 함수

**`async function`** 선언은 [`AsyncFunction`](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction)객체를 반환하는 하나의 비동기 함수를 정의합니다. 비동기 함수는 이벤트 루프를 통해 비동기적으로 작동하는 함수로, 암시적으로 항상 [`Promise`](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise)를 사용하여 결과를 반환합니다. 프라미스가 아닌 값을 반환하더라도 이행 상태의 프라미스(resolved promise)로 값을 감싸 이행된 프라미스가 반환되도록 합니다.

#### 1.문법

`async`는 function 앞에 위치합니다.

```js
async function name([param[, param[, ... param]]]) {
    statements
}

//예제
async function f() {
  return 1;
}
```

매개변수

- `name`

  함수의 이름.

- `param`

  함수에게 전달되기 위한 인자의 이름.

- `statements`

  함수 본문을 구성하는 내용.

- 반환 값Promise : async 함수에 의해 반환 된 값으로 해결되거나 async함수 내에서 발생하는 캐치되지 않는 예외로 거부되는 값.

#### 2. await

```js
// await는 async 함수 안에서만 동작합니다.
async function foo() {
    await 1
}

//위와 동일
function foo() {
    return Promise.resolve(1).then(() => undefined)
}
```

* `await` 키워드는 `async` 함수에서만 유효하다는 것을 기억하십시오. `async` 함수의 본문 외부에서 사용하면 [SyntaxError](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError)가 발생합니다.

*  따라서 `await` 문이 없는 `async` 함수는 동기적으로 실행됩니다. 하지만 `await` 문이 있다면 `async` 함수는 항상 비동기적으로 완료됩니다.

* `async` 함수가 아닌데 `await`을 사용하면 문법 에러가 발생합니다.

  * ```js
    function f() {
      let promise = Promise.resolve(1);
      let result = await promise; // Syntax error
    }
    ```

#### 3. 에외처리

async & await에서 예외를 처리하는 방법은 바로 [try catch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch)입니다. 프로미스에서 에러 처리를 위해 `.catch()`를 사용했던 것처럼 async에서는 `catch {}` 를 사용하시면 됩니다.

```js
async function f() {

  try {
    let response = await fetch('http://유효하지-않은-url');
    let user = await response.json();
  } catch(err) {
    // fetch와 response.json에서 발행한 에러 모두를 여기서 잡습니다.
    alert(err);
  }
}

f();
```

`try..catch`가 없으면 아래 예시의 async 함수 `f()`를 호출해 만든 프라미스가 거부 상태가 됩니다. `f()`에 `.catch`를 추가하면 거부된 프라미스를 처리할 수 있습니다.

```js
async function f() {
  let response = await fetch('http://유효하지-않은-url');
}

// f()는 거부 상태의 프라미스가 됩니다.
f().catch(alert); // TypeError: failed to fetch // (*)
```

